### ISSUE TITLE
[📚DOCS] 프로토타입 이미지 업로드

### ISSUE THREAD

**Issue by eas1w0n** [Dev-FE-3/team2-underdog-triptailor#14]
### 설명
README.md 파일에 필요한 이미지를 업로드한다.
### 할 일

- [x] 배너 이미지
- [x] 사용자 등록 및 관리 이미지
- [x] 여행 계획 이미지
- [x] 커뮤니티 이미지

**Comment by jiwonnayoung** [comment]
![Slide 16_9 - 1](https://github.com/user-attachments/assets/4c7599b5-0385-4212-9c50-4faa8a90082f)

배너 이미지

**Comment by eas1w0n** [comment]
![Slide 16_9 - 1](https://github.com/user-attachments/assets/25304ed0-730d-40f5-9519-c933a673b100)

배너 이미지 업로드

**Comment by eas1w0n** [comment]
![image 16](https://github.com/user-attachments/assets/fe0a0f43-47bf-4419-a043-e5e4dc1582c8)

배너 프로토타입 이미지 업로드

**Comment by eas1w0n** [comment]
![트립테일러_여행정보등록](https://github.com/user-attachments/assets/156cdede-c904-477c-b725-b4c24462175e)


![트립테일러_여행일정생성](https://github.com/user-attachments/assets/d4c9639c-952e-4b7c-ba82-261187f97d9d)

![트립테일러_커뮤니티](https://github.com/user-attachments/assets/bc96d3c5-31fb-4c86-b252-6d8503d95513)



- 사용자 등록 및 관리 이미지 업로드
- 여행 일정 생성&메이트 매칭 이미지 업로드
- 커뮤니티 이미지 업로드
