### ISSUE TITLE
[📚DOCS] 이슈 템플릿 작성

### ISSUE THREAD

**Issue by eas1w0n** [Dev-FE-3/team2-underdog-triptailor#5]
### 설명 
온보딩 프로젝트에 사용할 깃허브 이슈 템플릿을 작성합니다
### 할 일

- [x] 이슈 템플릿을 작성하여 커밋합니다

**Comment by j0n0m2** [comment]
아주 예쁘게 잘 만들어졌습니다~

**Comment by chjjh0** [comment]
아주 잘 됐네요 좋습니다~!!
